name: hyperparameter_tuning
program: models/train.py
method: random
metric:
  name: val_auc
  goal: maximize
parameters:
  lr: # 0.002
    values: [0.003]

  batch_size:
    values: [8]

  emb_dir:
    values: ["embs/facebook/esm2_t30_150M_UR50D"]
  head_type:
    # values: ["bilstm", "lstm", "bigru", "gru"]
    values: ["bigru"]

  hidden_size:
    values: [32]
  num_layers:
    values: [1]
  dropout: #0.62
    values: [0.6]

  epochs:
    values: [10000]
  num_workers:
    values: [24]
  seed:
    values: [42]
  patience:
    values: [4]
  weight_decay: # 0.0024
    values: [0.002]
