name: esm2_t33_650M_UR50D
lr: 0.001
batch_size: 16
head_type: bigru
hidden_size: 64
num_layers: 3
dropout: 0.5
epochs: 10000
patience: 5
seed: 42
num_workers: 1
weight_decay: 0.001
mask_ratio: 2
emb_dir: embs/idp/facebook/esm2_t33_650M_UR50D
shortcut: True
