name: prot_t5_xl_half_uniref50-enc
lr: 0.001
batch_size: 64
head_type: bigru
hidden_size: 256
num_layers: 2
dropout: 0.5
epochs: 10000
patience: 5
seed: 42
num_workers: 1
weight_decay: 0.001
mask_ratio: 2
emb_dir: embs/idp/Rostlab/prot_t5_xl_half_uniref50-enc
shortcut: True
