name: hyperparameter_tuning
program: models/train.py
method: grid
metric:
  name: val_auc
  goal: maximize
parameters:
  shortcut:
    values: [False, True]
  lr:
    values: [0.001]

  batch_size:
    values: [8, 16, 32]

  emb_dir:
    values: ["embs/rdp/facebook/esm2_t48_15B_UR50D"]
    # "embs/rdp/facebook/esm1b_t33_650M_UR50S"]

  # "embs/rdp/facebook/esm2_t6_8M_UR50D",
  # "embs/rdp/facebook/esm2_t12_35M_UR50D",
  # "embs/rdp/facebook/esm2_t30_150M_UR50D",
  # "embs/rdp/facebook/esm2_t33_650M_UR50D",
  # "embs/rdp/facebook/esm2_t36_3B_UR50D",
  # "embs/rdp/Rostlab/prot_t5_xl_bfd",
  # "embs/rdp/Rostlab/prot_t5_xl_half_uniref50-enc",
  head_type:
    # values: ["bilstm", "lstm", "bigru", "gru"]
    values: ["bigru"]

  hidden_size:
    values: [16, 32, 64, 128]
  num_layers:
    values: [1]
  dropout:
    values: [0.5]

  epochs:
    values: [10000]
  num_workers:
    values: [1]
  seed:
    values: [42]
  patience:
    values: [5]
  weight_decay:
    values: [0.01]
  mask_ratio:
    values: [2]
